### ISSUE TITLE
OCR-specific information

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#105]
It was requested that we make it clearer, which projects use OCR and which software is used.

**Comment by theodore-s-beers** [comment]
This would involve a schema change, right? Something for @XeniaMonika to think about?

**Comment by Jomula** [comment]
Yes it would, there are some other issues involving changes in the schema, so maybe it would be an idea to address them as a bundled schema change issue: #89, #68, #46

**Comment by XeniaMonika** [comment]
Ok! I will think about it and share with you the proposal for the new scheme as soon as I have it.

**Comment by XeniaMonika** [comment]
I have some new ideas regarding all these issues:

-as for sustainability, I just added it to research data, it could also be in policies, but it would require more changes, I think

- keywords:  in GUI they still look a bit chaotic. I would introduce categories form keywords documentation (which I have to rewrite) to make the search easer, and these would be
  a) language 
  b) field (linguistics, philosophy, etc.)
  c) research object (manuscripts, inscription, bible)
  d) output (catalogue, digital edition, research software)
  e) method (OCR, annotation) 
Feel free to change the names of the categories, if you have a better idea. If you are ok with it, it has to be changed in the scheme and added to our GUI

- tools specific info (like which OCR was used) could also be an interesting search criterium, so I would add in the GUI a search called "tools" which can be linked  to project/stack/tool/label. In this way people could find projects working with a tool of their interest very easily. 

- alternatively, we can put all these search categories together, so it would be something like that:
 Search Categories:
1. type (DH, Infra and so on)
2. language 
3. field 
4. research object 
5.  output 
6.  method 
7. tool (kraken, mallet, ...)


- siblings and cooperation... that is the tricky one. In our map the relations are not that clearly visible, especially when the sibling project is somewhere in ME or in the US. In this case you have to scroll down the map following the line that leads you to a cluster which you have to open again and find the right project, it takes time. Maybe it would be better to include this information directly in the project elements? Like "related to" or "cooperating with" under keywords? Or if we want be super DH, we can create a network graph showing ontological relations and cooperation.
And cooperation can be an important info, which we weren´t including until now if there was no ontological relation between the projects, so I would propose to add "cooperation" as a new relation type next to parent/sibling/child. 

Ok, that was lot... In templates I have uploaded a file in which  you can see how the template would look like if we did these changes. Be free to change it and comment it :)

**Comment by XeniaMonika** [comment]
Should I implement these changes? It would be nice to have at least the keyword sorted out before the conference in November. What do you think?

**Comment by theodore-s-beers** [comment]
The suggestions above sound good in principle. But something about this thread makes me feel like we should sit down and review the schema in a general way before making the next round of additions/changes.

**Comment by XeniaMonika** [comment]
Ok, I´m rewriting the keywords right now, I can upload it as a separate file without changing the scheme, so we can discuss about it. But generally,  I also think it will be a good idea to sit down together soon.

**Comment by XeniaMonika** [comment]
Moved to #150
