### ISSUE TITLE
Fix GUI formular

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#122]
JSONs generated in GUI are incorrect. Who should fix it?

**Comment by theodore-s-beers** [comment]
This is fixed now, right? If not, feel free to reopen.

P.S. When you make a pull request that will resolve an issue, you can [link to it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and have it closed automatically.

**Comment by XeniaMonika** [comment]
Ah, ok! Good to know for the next time. And yes, it´s fixed.
