### ISSUE TITLE
new project, should I add it?

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#133]
Are we interested in projects that are barely documented and almost no information can be found about them? For example, I have found a project called "The Digital Sirah Project" (https://kitab-project.org/about/funders#qatar-national-library-digital-sirah-project), a cooparation between KITAB and Qatar NL, but apart from a little description in the website above, there are no traces of it in the whole internet (except from here:  https://eldarion.com/scholarship/). The website of Qatar NL doesn´t mention it either. 
Generally, should I add this kind of things, or are they useless for us because the info is too little?

**Comment by theodore-s-beers** [comment]
We could reach out to [Kevin Jaques](https://religiousstudies.indiana.edu/about/faculty/jaques-kevin.html), a _sīrah_ specialist who was involved in the project. In fact, based on his faculty bio, it seems that he may still be working on "an open-access digital edition of the entire Ibn Ishaq collection."

**Comment by XeniaMonika** [comment]
Ok, thank you

**Comment by XeniaMonika** [comment]
I will save the project and add him as a contact person. By the way, contacting the projects is also something we should talk about on Monday. 
And wow! How did you find this info so quickly? I was looking for so long but I couldn´t find anything about this project, haha!

**Comment by theodore-s-beers** [comment]
I think I googled "Digital Sirah Project" with the quotation marks, to get more precise results.

P.S. I just merged a big PR. If you're working on anything right now, you'll probably need to rebase. Sorry if I've messed up your workflow a bit this morning.
