### ISSUE TITLE
Rewrite the datamodel

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#150]
1. Sustainability (#68) - add it to research data (see templates/project_proposal.json)
2. Keywords (will solve #89, #90, #105 )
3. Cooperation (#46, #89) - should we add it as the 4. category to relations (next to child, parent, sibling)?
4. Topic relations - should they be removed and added as a keyword category in line with the DHA topic ["Type"](https://vocabs.dariah.eu/dha_taxonomy/en/page/?uri=https%3A%2F%2Fvocabs.acdh.oeaw.ac.at%2Fdhataxonomy%2FCollection06)?

**Comment by theodore-s-beers** [comment]
Thanks for combining these issues.
