### ISSUE TITLE
Reimplement front end with SvelteKit

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#169]
When I started digging into the question of what changes need to be made to the front end, it became apparent to me that some kind of meta-framework should be used. i.e., if we stick with Vue, we should migrate to [Nuxt](https://nuxtjs.org/). That would, for example, allow for true static site generation.

But I don't have much experience in the Vue ecosystem. I think it will be faster for me—and probably will not make much difference to anyone else—to reimplement the front end with [SvelteKit](https://kit.svelte.dev/).

I'll use this as a tracking issue. My development of a Svelte app will be done initially in a [separate repo](https://github.com/theodore-s-beers/ctg-redux). And here's a link to a demo site:

<https://ctg-redux.pages.dev/>

This is still at an early stage. My intention is to make something that looks almost identical to the existing Vue app, whose design I think is good.

**Comment by theodore-s-beers** [comment]
@XeniaMonika, just letting you know that this is now in progress…

**Comment by XeniaMonika** [comment]
@theodore-s-beers , that´s great because I will be done with the new keywords soon and they will be ready for implementation in the GUI

**Comment by XeniaMonika** [comment]
I´m done with rewriting the keywords, so theoretically I could change in the front end right now. Should I wait with it until you are done with the migration to [SvelteKit](https://kit.svelte.dev/).?

**Comment by theodore-s-beers** [comment]
It wouldn't make a big difference to me, since I'm working on the reimplementation in a separate repo. Again, you can get a sense of how that's progressing at the following link:

<https://ctg-redux.pages.dev/>

I'm curious to see/hear what changes you have in mind for the front end. If I recall correctly, part of the plan was to divide the keywords into categories to make them more easily navigable?

**Comment by XeniaMonika** [comment]
Yes, the fields *categories* and *keywords* should be merged together into one drop-up list, which will contain new categories. The old *categories* (dh, nls, meta, rdm, infra) will be removed bcs I have keywords for them, and it doesn´t make sense to have them twice. So exactly as we said in our last meeting.

**Comment by theodore-s-beers** [comment]
Ok, that sounds good. Feel free to make changes in the source code of the existing Vue front end. It could be your next adventure…

**Comment by theodore-s-beers** [comment]
P.S. One thing I wanted in the front end is for it to be possible to point a URL directly at the list of projects matching a given keyword. That's now implemented. (It seems to work for me, but there may still be bugs.) Here's an example, for the keyword `research_data_management`:

<https://ctg-redux.pages.dev/#keyword=research_data_management>

**Comment by theodore-s-beers** [comment]
As of today, a project search function has been added:

<https://ctg-redux.pages.dev/>

This will close #99. In fact, I may close that issue now, since it's only a matter of time until we deploy the new site.

**Comment by MarwAhmed** [comment]
Theo, that's really good job! I had the same idea with the rewriting the app but using angular or react, I want to do something for NLS project, if you have a task for me? thanks a lot!

**Comment by theodore-s-beers** [comment]
> I want to do something for NLS project, if you have a task for me?

We should schedule a meeting soon with everyone involved in the project (incl. Prof. Gründler). Many things to figure out for the coming months…

**Comment by theodore-s-beers** [comment]
@XeniaMonika, I've added a "Languages" tab to the new front end. And it's possible to link directly to a specific language selection, as in the following example:

https://ctg-redux.pages.dev/#language=syr

**Comment by Jomula** [comment]
@theodore-s-beers what is your time schedule for reimplementing the new GUI? For getting the LoI, it would be good to have updated information on the website, especially the SUB and me being listed on the "About us" page asap.

**Comment by theodore-s-beers** [comment]
Everything is ready except for the contribution form. That ended up being sort of a low priority, since the form on the older site has been used by (afaik) only one outside contributor (and we had to make a lot of fixes to the data that it generated).

Anyway, I think we can "soft launch" the new site now. If there's any specific language that you'd like to see on the About page, I'll be happy to add it.

**Comment by Jomula** [comment]
That's great, if you don't mind I'd suggest to soft launch now. Just add me with the affiliation (Digital Scholarship Services, State- and University Library Hamburg Carl von Ossietzky) to the list of iniatives and institutions.

Thanks!

**Comment by theodore-s-beers** [comment]
Ok, I've done that. I placed the code for the new front end in a new branch in this repo, `gui-redux`. As with the original `gui` branch, there's a script to push build output to the `gh-pages` branch, from which the site is actually hosted. The `gui` branch can be left in place, at least for the foreseeable future. No reason to make destructive changes…

**Comment by theodore-s-beers** [comment]
Closing as resolved. Discussion of the reimplemented contribution form can move to #297.

**Comment by theodore-s-beers** [comment]
I'm going to delete the old `gui` branch, just to reduce visual clutter. The last commit there was 1f6d748.
