### ISSUE TITLE
ISO-639-2 does not cover some historical languages

### ISSUE THREAD

**Issue by Maroussia** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#179]
While filling up the JSON form to add a new project, I realised that by using ISO-639-2 for the languages of the project data, some languages cannot be represented, like Kanbun (old Japanese) or Old Chinese. Is there a way to overcome this limitation of ISO-639-2?

Thanks a lot for considering this side issue!

**Comment by theodore-s-beers** [comment]
Do you think we should move to [ISO 693-3](https://iso639-3.sil.org/about)? I'm open to the idea.

**Comment by Maroussia** [comment]
As far as I can see ISO 693-3 does not include Kanbun for instance. Maybe a way can be found that allows a certain flexibility? Something like a field with `other` where scholars could add themselves non-represented languages? And/Or a comment section for languages which gives the possibility to explain the specificity of the language in question? These are just some ideas...

**Comment by theodore-s-beers** [comment]
My guess is that Kanbun doesn't have a 639-3 code because it was considered a system/style used historically in Japan for writing and annotating Classical Chinese. If that's the case, you might need to use the codes `lzh` and `jpn` together when referring to Kanbun material. And if it should be categorized as a language, submit a request to SIL! They claim to want to cover "all known human languages," and there are currently on the order of eight thousand codes.

For our purposes, I would be open to migrating to ISO 639-3, and to adding a "comment" field to the schema.

**Comment by XeniaMonika** [comment]
In the keywords documentation, I wrote that the use of ISO 3 is possible when the new language is not a part of ISO 2 (which I also had to do myself a couple of times). The disadvantage of this approach is that we have two code systems in our data.  And we also have a comment section already, it is at the very end of the JSON file, after keywords.

**Comment by Maroussia** [comment]
I agree with you, having ISO 2 and 3 is confusing and should only be a temporary solution.

The keyword documentation is great by the way! Any chance you could add a link to it on the main `README` in the `Contribute` section so that users know it exists when they want to contribute? It is easy to overlook it.

I did use the comment section at the end for the language, as you suggest, but I feel like having one specific to languages could be more inclusive and user-friendly, in the sense that it would indicate to the users that you are aware of the limitations of ISO 2 and ISO 3, and you welcome those which do not fit. 

Another solution would be to add a simple comment above/under the languages box(es) to encourage using the `comment` box at the end of the form in case the languages are not in ISO. This would avoid making too many changes while at the same time guiding users on what to do.

**Comment by theodore-s-beers** [comment]
I think that, if we're already in a situation where we sometimes have to use 639-3 codes, we should switch to that entirely. It shouldn't be a difficult migration. Things like this can be scripted (as @XeniaMonika well understands!).

It doesn't need to be a priority, but I think it's worth doing at some point.

**Comment by theodore-s-beers** [comment]
re: adding a language-specific comment field, now I find myself leaning against it. I want to take a conservative approach to expanding the schema—and I had forgotten that there's already a general comment field.

**Comment by Maroussia** [comment]
This is a good point. Simplicity is always to be preferred, I agree! So I guess either having a line pointing to the comment field or adding it to the `keyword-documentation` could be a simple fix, and potentially adding a link to this documentation in the `contribute` section of the `README` :)

**Comment by XeniaMonika** [comment]
Thank you for your suggestions @Maroussia! I have just applied them :)

**Comment by XeniaMonika** [comment]
I think it is OK to close this issue now
