### ISSUE TITLE
Look into Zod for schema validation

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#231]
I recently came across this project:

- Website: https://zod.dev/
- GitHub repo: https://github.com/colinhacks/zod

I think this could be a more modern, better-maintained solution for us to validate project JSON files against our schema. The fact that it's TypeScript-first is appealing to me. I'll look into it, with this as a tracking issue.

If others have opinions on this, do feel free to chime in.

**Comment by theodore-s-beers** [comment]
I got a Zod version of our schema working. For the moment, it's at the following repo:

https://github.com/theodore-s-beers/ctg-zod-validation

This already helped me to find several little errors in our data. (@XeniaMonika, you may notice my flurry of PRs dealing with dates, UUIDs, etc.)

I think we should switch to this for validation. I just need to figure out how to get it to run in CI.

**Comment by XeniaMonika** [comment]
Wow, it looks great! It indeed spots a lot more mistakes than our current validation! I´d be definitely for switching to it!

**Comment by theodore-s-beers** [comment]
Ok, it's done. We have a working Zod schema at `SCHEMATA/project_schema.ts`. Note that I've set this up with TypeScript and [Deno](https://deno.land/). It may be another new framework for you to get familiar with. There's a separate file in the `SCHEMATA` directory, `schema_tests.ts`, which describes the tests to be run against the schema. I'm flexible re: the naming and placement of these files. We can make changes as appropriate.

The new tests will run on all PRs to master, and I've disabled automatic runs of the previous workflow. It should feel like a drop-in replacement in terms of CI.

One advantage of this new approach is that it would be easy to run the validation tests locally, before making a commit or opening a PR on GitHub. You (or anyone else) can clone the repo and run `npm test`. The only catch is that you would need to have Deno installed—but that's no hardship.

Hopefully this will help us to clean our data and to continue refactoring the schema. (I have more thoughts on that front. I think the `research_data.data` section of the schema should be simplified. The way there are fixed independent sections for `raw`, `refined`, and `final` data seems over-engineered. Really this section should just be an array of objects, with each object representing a "datatype." And there could be a field to specify the "stage" of a given datatype, e.g., "refined." That would retain all of the descriptive power of the current structure while taking some bulk and repetition out of the schema. Anyway, we can discuss this further soon.)

**Comment by XeniaMonika** [comment]
I´ve just set it up and it works fine. I have just one question, why do we still need the project.schema.json and validation.yml files? Are we still using them somehow or can they be deleted?

**Comment by theodore-s-beers** [comment]
We should probably mark the JSON schema as archived, and perhaps move those files into a different directory. I wouldn't delete them. When it comes to the old validation workflow YAML, that could be deleted at some point. I started by editing it to disable automatic run on PR to master. How about we wait a bit to make sure that the new CI is working properly (esp. when you add new projects)?

**Comment by theodore-s-beers** [comment]
> Hopefully this will help us to clean our data and to continue refactoring the schema. (I have more thoughts on that front. I think the `research_data.data` section of the schema should be simplified. The way there are fixed independent sections for `raw`, `refined`, and `final` data seems over-engineered. Really this section should just be an array of objects, with each object representing a "datatype." And there could be a field to specify the "stage" of a given datatype, e.g., "refined." That would retain all of the descriptive power of the current structure while taking some bulk and repetition out of the schema. Anyway, we can discuss this further soon.)

I've now made this change, or at least an initial attempt at it. @XeniaMonika, you may want to review my recent PR that touched almost every file in the repo. What I found is that we don't have any datatype or repository recorded for any project in our collection, except one: Coptic OCR. Everything else could be changed en masse to fit the updated schema.

Honestly, I think we could go a bit further. There are still parts of the schema that strike me as repetitive or unnecessarily complicated. It's easy to make changes now, while most of the fields are still empty in most of the JSON files.

**Comment by XeniaMonika** [comment]
Should we register it in the changelog and change the schema version, or would you like to wait until we add more simplifications?

**Comment by theodore-s-beers** [comment]
I think we could do just a bit more streamlining before bumping again. Soon, though!

**Comment by XeniaMonika** [comment]
Ok. There is also one more change I´d like to do regarding the host institutions since some of them are not hosts but just members of organizations like Dariah. I would change `host_institutions` to `related_institutions`  and add a `relation_type` key with values of either `host` or `member`. Accordingly, I would also change `relations` to `related_projects`. If you are ok with it, I could do it directly.

**Comment by theodore-s-beers** [comment]
I definitely support making changes in those areas. One confusing detail is that `relations` are supposed to refer to other projects or organizations that we already have in our database. i.e., there should be a link to a UUID. And that is not the case for `host_institutions`. Do you have an idea for making this consistent?

**Comment by XeniaMonika** [comment]
We could rename `relations` to `related_entities` to include organizations. `Rlated_institutions` would be a separate key in the `project` item. So basically there wouldn´t be such a key as relations anymore.

**Comment by XeniaMonika** [comment]
Exactly. Would that mean we bump the schema or do you still want to make more changes in the ` research_data` section?

**Comment by theodore-s-beers** [comment]
I think you can bump the version after this. It might take me a few weeks to get back to the question of "datatypes" and repositories.

**Comment by theodore-s-beers** [comment]
@XeniaMonika, I noticed something else in the schema that might be possible to simplify—though I'm not 100% sure.

We use the `ref` key _mostly_ for URLs pointing to authority records. This comes up in a few places in the schema. There's `ref` for a project/organization itself; for a place (GeoNames URL); for an institution; for an individual (listed under `contacts`); and for a policy.

`ref` is always defined as an array of strings. i.e., we can list multiple URLs. Is this appropriate in all cases? For projects/organizations, institutions, and people, I think it is. There are sometimes authority records from multiple sources. But for a place, we just want a single GeoNames URL, don't we?

How would you feel about flattening `place_name.ref` from array of strings to simply a string? Or are there cases where we need more than one URL there?

P.S. What is a "policy," again? Have we ever used that part of the schema?

**Comment by XeniaMonika** [comment]
Theoretically, we could replace the array with a string in `place_name.ref` because we use only GeoNames. But we left it an array for consistency reasons - all `refs` should be of the same type. This is also how the schema is written, right? There is one definition for all URIs and all of them are arrays. I´m not sure if making one of them an exception would really simplify things.

**Comment by XeniaMonika** [comment]
And I´m myself not sure what Jonas meant by `policies`. I asked him once but I forgot. Is it somehow related to open access policies @Jomula?

**Comment by theodore-s-beers** [comment]
> This is also how the schema is written, right? There is one definition for all URIs and all of them are arrays.

True, that is how the JSON Schema was set up. In the Zod reimplementation, it sort of doesn't matter. Everything is defined in-place. (Maybe that's worse? Should we think about adding some abstractions back in?) We specify an array of URLs as follows:

`z.array(z.string().url())`

Which could be simplified to the following:

`z.string().url()`

But you're right: it's a very small point in any case. Just a chance to remove one layer of nesting from one place in the schema.

**Comment by Jomula** [comment]
As far as I can remember, I used `policies` as a property for "Open Source Policy" or "Open Science Policy" or "Research Data Management Plan" or stuff like that. In the beginning I hoped to get information in there if projects have or apply to these policies, but in reality, one can be happy if they know what this is anyway. So I wouldn't drop it, but it has not the highest priority, I guess.

As for the consistency of the `ref`, from the perspective of data curation, I'd not change it to String, as there are indeed other geo authorities (like wikidata), which might be of use in some case. Highly unprobable since we are working with modern data and not some obscure historic terms, but still. 

However, I agree that an array might be useless in the way we use it right now.

**Comment by theodore-s-beers** [comment]
Ok, we can leave these sections as they are.

**Comment by theodore-s-beers** [comment]
I'm going to close this. The Zod setup seems to be working well, and it's been a while since we last needed to change the schema.
