### ISSUE TITLE
JSON Validator for Pull Requests

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#25]
Fix Action to apply to Pull Requests before merging

**Comment by XeniaMonika** [comment]
I have changed the jml file some time ago to trigger the action on my push (so that I don´t have to make a pull request every time I want to see it the data is correct). 
There are two triggers now, one on my push nad the other on PR, should the second one be deleted?

**Comment by theodore-s-beers** [comment]
If you push directly to `master`, you'll never see whether the validation passed. If you do some work in a separate branch and then push it to GitHub (good idea), the check will run, and when you open a PR, you'll see whether it passed. Then you can merge into `master`.

The issue that you've noticed is that the validation workflow is currently running twice: once on push, again on PR. If you'd like to get rid of one of those, I think it's ok. What's important is that we maintain the good practice of using feature branches, opening PRs, and making sure that checks pass before merging.

**Comment by XeniaMonika** [comment]
Ok, so we changed the file to
on:
  push:
    brachnes:
      - xk
      - master 
  
 the action will be also triggered if someone pushes directly into master (which I never do, but if someone else wants to contribute it may happen). I would delete the one on PR, bcs it is less convenient for me. If you are ok with it, I will change the file

**Comment by theodore-s-beers** [comment]
It will never actually run on push to `master`. Usually that branch is excluded from workflows that run on push.

Another option I've seen is to have a workflow that only runs on PR to `master`.

**Comment by XeniaMonika** [comment]
Ah, OK. I didn´t know that. The second option is what we already have, right? 
on:
  push:
    brachnes:
      - xk
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  
As you said, I can just delete one of those.

**Comment by theodore-s-beers** [comment]
Yeah, if you prefer, you can get rid of the whole `push` section. Then you just need to wait a bit after opening a PR to allow the validation to run.

**Comment by theodore-s-beers** [comment]
I've verified that this is now working as intended: validation runs on PR to `master`.

Btw, I should correct one of my comments from yesterday. Workflows *can* run on push to `master`. You might do that if you wanted, e.g., for a site to be deployed any time that the main branch is updated. It's just that, for a use case like JSON schema validation, the whole point is to see the result before merging into `master`. So there would be no use in having the check run on a direct push to `master`.

Workflows that are intended for code review are often configured to run on push to any branch *other* than `master`, and on PR to `master`. (That does mean that they would run twice on each PR. I've seen this same issue before, and I never quite understood why people aren't bothered by the waste.)
