### ISSUE TITLE
Test new contribution form

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#297]
The reimplemented website is live, and there is a functioning (as far as I can tell) contribution form. @XeniaMonika, could you please test the form? I've done so already, but you'll know better. Does the download function work? Does the output JSON pass schema validation? Are there important fields or capabilities that are missing from the form in its current state? I'm sure there are, but the idea was to implement something very basic, then build back up to the feature set that is needed in practice.

**Comment by theodore-s-beers** [comment]
Could you share the details of that API call here? Not a bad idea to improve documentation of our workflow…

**Comment by XeniaMonika** [comment]
Sure. I´m still using Jonas's account. Is it @Jomula? We can also create our own.

So for example, this is the API of Berlin
http://api.geonames.org/getJSON?geonameId=2950159&username=jomla&style=short&formatted=true

As you can see each city has its own ID, you can find it in the GeoNames `ref`:  https://www.geonames.org/2950159/berlin.html
In this Berlin´s case, it is 2950159, the same ID is also in the API link, so for other cities you just need to get it from the ref and paste it into the API. This is the Python code I use:

```
import urllib.request, json  
import re
#get the coordinates from geonames 
                api_link_1="http://api.geonames.org/getJSON?geonameId="
                api_link_2="&username=jomla&style=short&formatted=true"
                
                
                def add_lat_and_lng():
                    ref=d.get("place_name").get("ref")
                    if ref!=[]:
                        number=re.findall(r'\d+', ref[0])[0]
                    link=api_link_1 + number + api_link_2
                    with urllib.request.urlopen(link) as url:
                        api_data = json.loads(url.read().decode())
                    d["coordinates"]["lat"]=api_data.get("lat")
                    d["coordinates"]["lng"]=api_data.get("lng")
                            
                for d in places:    
                    if d.get("coordinates").get("lat") == "0":
                        add_lat_and_lng()
```

**Comment by XeniaMonika** [comment]
As I said, I could gladly do it as a little exercise ;)

**Comment by Jomula** [comment]
It is probably best to create a project account for the GeoNames API, I don't need mine right now, but it is generally best to have it project-specific.

**Comment by XeniaMonika** [comment]
Ok, I´ll do it right now!

**Comment by XeniaMonika** [comment]
Ok, I´ve created an account for our project. Our user name is **closing_the_gap**
That the updated API link for Berlin: 
http://api.geonames.org/getJSON?geonameId=2950159&username=closing_the_gap&style=short&formatted=true
```
api_link_1="http://api.geonames.org/getJSON?geonameId="
api_link_2="&username=closing_the_gap&style=short&formatted=true"
```

**Comment by XeniaMonika** [comment]
I think we are done with this one, right?

**Comment by theodore-s-beers** [comment]
Yeah, probably. There are still improvements that could be made, but the initial issues are solved.
