### ISSUE TITLE
Short or long paper for DHd 2024

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#298]
I'd suggest to hand in a paper (1500-2000 words) or poster (500-750 words) for the next DHd in 2024. We can use the skeleton for the other paper, I'd offer to write an Aufschlag. What do you think? What would you prefer, paper or poster? @theodore-s-beers @XeniaMonika 

CfP: https://dhd2024.dig-hum.de/call-for-papers/

Deadline is 2023-07-19

**Comment by theodore-s-beers** [comment]
I actually don't have a strong preference between paper and poster. What do you two think?

**Comment by XeniaMonika** [comment]
Would paper also mean that we´ll have to make an oral presentation? Except for the length, I´m not sure what the difference exactly is.

**Comment by Jomula** [comment]
Poster means we have to make a nice poster, present it at the poster session and be present for people who visit to talk to. It is generally easier to be accepted with a poster, it is far less "official", since there is no talk or presentation but depending on where the poster is set up it might be less public.

Paper would mean that we have a 30-40min slot with a presentation and Q&A. Less probable to be accepted but "more fame".

**Comment by XeniaMonika** [comment]
So maybe we can go for more fame this time? ;)

**Comment by theodore-s-beers** [comment]
Do they offer fallback to the possibility of a poster presentation for paper abstracts that aren't accepted? It wouldn't be a bad idea. I guess I feel a bit skittish after our last rejection, which never made sense to me.

**Comment by Jomula** [comment]
There is sometimes an option for peer reviewers to suggest an application rather as a poster, but I don't know how it is here. And true, the last rejection is not much of a motivation, but this was DH and here we would apply for the DHd, which is much less big and we had this huge discussion on "Kleine Fächer", which might lead to the committee being more sensitive in that regard.

**Comment by theodore-s-beers** [comment]
Then let's go for a paper. We can make another good-faith effort and see how it's received. As you said, DHd may look more kindly on us as a more focused organization.

**Comment by theodore-s-beers** [comment]
Closing this for now, since our proposal was submitted (thanks to Jonas)…
