### ISSUE TITLE
Continue testing website/UI

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#316]
I've re-added the feature on the website whereby keywords are shown in groups. Thanks again to @XeniaMonika for devising this system. Since there have been several UI changes recently, I think it would be good if we spent a bit of time clicking around the website, looking for things that need to be fixed or improved. (e.g., the layout of keyword groups is messed up on mobile. I'll take care of that soon.)

**Comment by XeniaMonika** [comment]
I was clicking through our website and have seen that the languages in the project items (in the search tab)
are now languages of websites. Maybe it´d be better to have there the research languages instead, bcs now you can´t see this information anywhere in the projects list. I could do it quickly.

**Comment by theodore-s-beers** [comment]
Do you mean the language codes in the project cards? I think it was the same way in the old website. But I may be wrong about that. In any case, we could think about changing it.

**Comment by XeniaMonika** [comment]
I think it was the same in the old website. But still, research languages make more sense in my opinion.

**Comment by theodore-s-beers** [comment]
Closing for the time being…
