### ISSUE TITLE
Add project

### ISSUE THREAD

**Issue by tillgrallert** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#317]
I filled in the form at https://m-l-d-h.github.io/Closing-The-Gap-In-Non-Latin-Script-Data/contribute/ and tried to attach the resulting JSON to this Issue. However, JSON is not supported for issues. I therefore zipped the JSON.
[4ed4b218-0a06-4ae1-857a-1d87a9371e08.json.zip](https://github.com/M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data/files/11999403/4ed4b218-0a06-4ae1-857a-1d87a9371e08.json.zip)

**Comment by theodore-s-beers** [comment]
Thanks! Sorry about the JSON attachment issue. You're the first to try this workflow… which will need to be rethought.

**Comment by tillgrallert** [comment]
Thank you very much. It is weird that GitHub doesn't allow to upload JSON files while ZIP files are perfectly fine.

**Comment by theodore-s-beers** [comment]
Yeah, I guess a lot of people have been surprised by this restriction. e.g.

https://github.com/orgs/community/discussions/42494

I'll probably update the script on the website so that it generates a `.txt` file. Then we would need only to change the extension each time.
