### ISSUE TITLE
Enable project submission by email

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#327]
Instead of attaching to a GitHub issue, people could email us the generated JSON file. This should be explained on the contribution form.

**Comment by theodore-s-beers** [comment]
@XeniaMonika, this might also be something that you could work on. The first step is just to update the explanatory text in the contribution form.

**Comment by XeniaMonika** [comment]
Sure!

**Comment by XeniaMonika** [comment]
One question, which email should I use? Do we have a project-specific email address? Or should we get one?

**Comment by theodore-s-beers** [comment]
> One question, which email should I use? Do we have a project-specific email address? Or should we get one?

I think there used to be a project email address, but my recollection is that it was basically a random string of characters, which I didn't like. What do you think we should do? Use our own FU addresses, or get a meaningful one for the project?

**Comment by XeniaMonika** [comment]
I think we should get a better one for the project
