### ISSUE TITLE
Implement Credit Taxonomy for the project

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#338]
Since the project is growingly not simply a local FU-internal thing, how about implementing [CRediT](https://credit.niso.org/) for all contributors to the project? This could be done so it is visible on the frontend but also in the Readme/Documentation and can also include dates, to account for changes in staff or roles. What do you think?

**Comment by XeniaMonika** [comment]
So we would label first all 4 of us. Should we also somehow credit people that contribute their data? We have 2 such cases already.
What about these roles?
Ms. Gründler [Supervision](http://159.203.176.220/contributor-roles/supervision/) 
Jonas [Conceptualization](http://159.203.176.220/contributor-roles/conceptualization/) and [Methodology](http://159.203.176.220/contributor-roles/methodology/)
Theo [Software](http://159.203.176.220/contributor-roles/software/), [Visualization](http://159.203.176.220/contributor-roles/visualization/), [Validation](http://159.203.176.220/contributor-roles/validation/) and [Formal Analysis](http://159.203.176.220/contributor-roles/formal-analysis/)
Xenia [Data curation](http://159.203.176.220/contributor-roles/data-curation/) [Formal Analysis](http://159.203.176.220/contributor-roles/formal-analysis/), [Investigation](http://159.203.176.220/contributor-roles/investigation/)

Just spontaneous ideas, feel free to change anything

**Comment by theodore-s-beers** [comment]
Should this be in the form of a Markdown document? If so, what should we call it? Something like `CONTRIBUTORS.md`? And should we place it at the root of the repository?

**Comment by Jomula** [comment]
We could just write it in a markdown file and refer the roles to the taxonomy. We could also write it in a proper XML file to have the role refered in the `<role />` tag, as suggested by CRediT. Or we do something inbetween and make a `yaml` or `json` file for the purpose and map the XML-tags to the respective language?

**Comment by theodore-s-beers** [comment]
I looked at the [implementation guidelines](https://credit.niso.org/implementing-credit/), and it wasn't immediately clear to me which level we should target. If it's important that we produce XML, then of course we can do so. But I think a Markdown document with a table could be a good starting point. e.g.,

| Contributor Role       | Contributor Name(s)                                                        |
| ---------------------- | -------------------------------------------------------------------------- |
| Conceptualization      | Jonas Müller-Laackman (2021 – present)                                     |
| Data Curation          | M. Xenia Kudela (2021 – present)                                           |
| Formal Analysis        | M. Xenia Kudela (2021 – present)                                           |
| Funding Acquisition    | Beatrice Gründler (2021 – present)                                         |
| Investigation          | M. Xenia Kudela (2021 – present)                                           |
| Methodology            | Theodore S. Beers (2022 – present), Jonas Müller-Laackman (2021–22)        |
| Project Administration | Theodore S. Beers (2022 – present), Jonas Müller-Laackman (2021–22)        |
| Software               | Theodore S. Beers (2022 – present), Jonas Müller-Laackman (2021–22)        |
| Supervision            | Beatrice Gründler (2021 – present), Jonas Müller-Laackman (2023 – present) |
| Validation             | Theodore S. Beers (2022 – present), Jonas Müller-Laackman (2021–22)        |
| Visualization          | Theodore S. Beers (2022 – present), Jonas Müller-Laackman (2021–22)        |

Also, I found a [concise reference on contributor roles](https://www.cell.com/pb/assets/raw/shared/guidelines/CRediT-taxonomy.pdf) from Cell Press. Perhaps we can link to that (or to something similar).

**Comment by Jomula** [comment]
I agree, a markdown table would be fine for now. Should we offer TEI export in the future, we can add the information XML encoded in the teiHeader. But I'd include links from the contributor role labels to the CRediT entries.

**Comment by theodore-s-beers** [comment]
I've added a `CONTRIBUTORS.md` file at the root of the main branch. Each role label has a link, as you suggested.

**Comment by theodore-s-beers** [comment]
I'll close this issue for the time being. If/when we need to change our approach to CRediT, we can either reopen this or create a new issue.
