### ISSUE TITLE
Re-implement keywords and tagging categories

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#340]
I´m done with the tags and will soon start working on new keywords categories for the GUI. I have some more data like: is the output or content available, if not, isn´t it available yet or not anymore, that could be a point for sustainability.  And some comments. I could also upload them here as CSV files. Do you think I should?

**Comment by theodore-s-beers** [comment]
Assuming the CSV files aren't too large, and that they can be attached to a GH issue (we recently discovered that JSON attachments are prohibited), I think this sounds like a good idea. Or do you just mean that you could add the CSV files to the repository?

**Comment by XeniaMonika** [comment]
I meant to the repository, as we want to be transparent. We could use this data for our publication and for visualizations, so maybe it´ll be good to have them somewhere. Maybe we can talk about it tomorrow

**Comment by theodore-s-beers** [comment]
@XeniaMonika, the new keywords and categories are done now, right? Should the keywords documentation file also be updated?

Also, how (if at all) do you want to move forward with the CSV files?

**Comment by XeniaMonika** [comment]
Yes, they are ready. Ißm working on the documentation and I´ll add it to the changelog

**Comment by XeniaMonika** [comment]
And maybe we can talk about the CSVs in our next meeting? Otherwise, I could put them in the `KEYWORDS` folder.
Or maybe we can upload them first when we have some visualizations since I´ll need them for the code.

**Comment by XeniaMonika** [comment]
I´ve closed it since the new keywords are done. We can add the CSV when we add the visualizations.
