### ISSUE TITLE
GUI - filter option

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#354]
We should reimplement the search bar to enable filtering the projects by marking multiple tags at once. See an [example](https://projektbrowser.berliner-antike-kolleg.org/)

**Comment by theodore-s-beers** [comment]
I think we could start by allowing for just two keywords to be selected at a time. Then, if that worked ok, we could think about enabling larger intersections.

**Comment by theodore-s-beers** [comment]
Having now worked on this feature, I realized it's easier to change our code to allow an arbitrary number of keywords or language tags to be selected.

**Comment by theodore-s-beers** [comment]
Closing as completed for now. This can be reopened later, or a new issue filed, for further development of the feature.
