### ISSUE TITLE
Update schema changelog

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#371]
The schema version has been bumped to `0.2.0`. All tests are passing. @XeniaMonika, could you update the changelog? There were only three actual changes made to the schema since `v0.1.9`. See the following commits: 7f613de, ca2048d, c0e3b41. Many thanks!

**Comment by theodore-s-beers** [comment]
@Jomula, this is the version bump to `0.2.0` that we discussed at a recent team meeting. I thought it might have been done already. Now it may be necessary to issue another release. Sorry for the extra churn.

**Comment by XeniaMonika** [comment]
Closed with #384
