### ISSUE TITLE
Qalamos / Best Practices

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#409]
At the opening of the second project phase of Qalamos, the issue of how to inform the academic public about the (best) practices of the project was being discussed. I think we could step in here and offer them to complete their dataset. What do you think?

**Comment by theodore-s-beers** [comment]
What would completing their dataset mean, exactly?

**Comment by Jomula** [comment]
Reach out to them and do an interview or something like that to get more information on the dataset. I think you want to do that with some exemplary projects anyway, don’t you? You could include qalamos in that list.

**Comment by theodore-s-beers** [comment]
I believe @XeniaMonika has been in touch with them (or at least, they're on our list), so I'll close this for the time being.
