### ISSUE TITLE
Adding `maintained` field to schema

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#420]
I did the first steps of this in #419. There is now a `maintained` field, pretty much at the top level of the schema. I didn't see an existing category in which it seemed to belong.

`maintained` is currently defined as a nullable boolean. i.e., it should be `true` or `false`, but it can optionally be `null`, at least for the time being, while we work to update existing entries.

I've also added this field to every current database entry. And it's `null` everywhere—but this is just a starting point. All tests are passing, and we can improve our data over time. I do have some ideas for detecting entries for which `maintained` must be `true`. For example, we can search for projects that have defined funding periods that are still active. I would be comfortable saying that currently funded == maintained. (The entire problem is that the inverse does not hold…)

Anyway, if this field doesn't work out for one reason or another, or if it proves more hassle than it's worth, we can always remove it. @XeniaMonika, we should probably bump the schema version (to `0.2.2`?). @Jomula, this may become an occasion for publishing new releases on GitHub and Zenodo.

**Comment by theodore-s-beers** [comment]
In #421, I was able to set `maintained` to `true` for 56 entries (or some number close to that). I just wrote a script to identify projects that have defined funding periods that continued at least into 2023. Those are now marked as maintained as a matter of course. Separately, it occurred to me that most _organizations_—though not all—remain active over a longer period of time. So I looked at those as well, and felt comfortable setting `maintained` to `true` in all but a few cases.

**Comment by XeniaMonika** [comment]
I have bumped the schema and set the `maintained` value to `false` for 11  projects I have already marked as such during my research for the taxonomy.

**Comment by XeniaMonika** [comment]
closed with #423

**Comment by theodore-s-beers** [comment]
Ok. We can leave the issue "closed," while continuing to update our records. Should just remember to follow up with Jonas about publishing another release of our schema and database.

**Comment by Jomula** [comment]
Reopened for release task

**Comment by Jomula** [comment]
Reopened because I still need to do the release :P

**Comment by XeniaMonika** [comment]
Sure! My bad

**Comment by Jomula** [comment]
Made a release: https://zenodo.org/records/10391227
