### ISSUE TITLE
Icon ambiguity

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#424]
The Icon for "code" shows "</>", but we use JSON. So either we should swap it to "{ }" or offer an additional .xml transformation :D

(should have thought about that in the very beginning)

**Comment by theodore-s-beers** [comment]
Ok, I swapped out the icon. I wasn't thrilled with any of the options that I found for curly brackets, but I used the one that seemed least bad. XML can wait for another day…

**Comment by theodore-s-beers** [comment]
Wait, it isn't working right. We lost the hover effect. I'll try to fix it.

**Comment by theodore-s-beers** [comment]
Fixed this (I think) in a1d02f0ecd123d4073aa4414f0860dc39fd47906.
