### ISSUE TITLE
Check newly added entry

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#462]
@XeniaMonika, when you get a chance, could you double-check our data on the project "Prosopografía de los ulemas de al-Andalus" (directory `pua`)? Maxim sent me a JSON file. I then made some changes (most recently in #461) so that it better fits our conventions. But I think it wouldn't hurt for you to have a look as well. Thanks!

**Comment by XeniaMonika** [comment]
Done!
