### ISSUE TITLE
Enrich majlis dataset

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#474]
I just got a msg with this article: https://malisprojekte.web.th-koeln.de/wordpress/manuforma-katalogisierung-von-handschriften-im-browser/ and realized that they have a github repo: https://github.com/majlis-erc

-> We should at least add the github repo to the dataset
-> Mabye this would also be an interesting project for a short-term interview?

**Comment by theodore-s-beers** [comment]
@XeniaMonika and I spoke about this briefly, and will make sure we add it to our DB.

**Comment by XeniaMonika** [comment]
closed with #493
