### ISSUE TITLE
Add new team member as contributor

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#567]
We now have @christiancasey officially as part of the project team. @Jomula, can you advise on getting him added to this repo? Thanks!

**Comment by Jomula** [comment]
Invited him as admin!

**Comment by christiancasey** [comment]
Got the invite. I’m still getting setup here and I don’t have a computer in front of me right now, but I’ll put on my todo list to accept the invite as soon as I can. Thank you both for your help,ChristianAm 10.12.2024 um 08:48 schrieb Jonas Müller-Laackman ***@***.***>:﻿
Closed #567 as completed.
