### ISSUE TITLE
Fix table head and first col @timeline view

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#62]
Either fix table head and first col so it is easier to navigate the timeline or switch to visualisation library

**Comment by theodore-s-beers** [comment]
Here's the reimplementation of the timeline: https://ctg-redux.pages.dev/timeline

I've fixed the header row, and limited the number of years that are shown so that the first column doesn't get lost. I still want something better for the timeline, but I think we can close this specific issue.
