### ISSUE TITLE
Consider running GitHub Pages from a separate branch?

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#69]
It might clean things up a bit to keep the data in the main branch (possibly along with the frontend source code, as it is now), but have the Vue build output deployed to a separate branch, `gh-pages`, and then point GitHub Pages to that branch. This is a popular pattern that I've found helpful in other projects.

**Comment by theodore-s-beers** [comment]
Here's a link to the package I've used for this:

https://www.npmjs.com/package/gh-pages

**Comment by Jomula** [comment]
Done that, GUI src files and build are available on gh-pages branch.
