### ISSUE TITLE
Clear stale branches?

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#77]
It looks as though the only two branches currently in use are `master` and `gh-pages`. It might be helpful to clean up the others. I was a bit confused by the presence of the `gui` branch, which saw activity as recently as two months ago. But my understanding is that the frontend code is now being kept in `gh-pages`?

Perhaps I'll wait a few days to see if people raise objections, and if not, I'll delete the older branches. (They can always be restored.)

**Comment by Jomula** [comment]
you're right, the `gui` branch is obsolete, I think I meant it to be what `gh-pages` is now. Anyway, deleted it already. :)

`projects.0.0.9` is an archived version - I think - of the projects with an old schema. I'll have a look later.

**Comment by theodore-s-beers** [comment]
I'm going to delete the `projects_0.0.9` branch. In case someone wants to restore it, the latest commit was 415f2a308b51917edcb35ebc57e27e4a9e6c3964.
