### ISSUE TITLE
How is Vue build output passed to the parent directory?

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#82]
I've been trying to figure out the workflow here before making some changes (e.g., adding Dependabot and some new CI stuff). I get that GitHub Pages is pointed to the `gh-pages` branch. In that branch, the Vue build output is in the root directory, while the source code is in the `GUI` subdirectory. (Fwiw, I think this is a bit of an unusual setup. What I would expect would be for the frontend source code to be at the root of its own branch, and then there would be a deploy script that automatically pushed build artifacts to the root of `gh-pages`.)

Anyway, if I run the build command from `/GUI`, it outputs to `/GUI/dist`. What I'm wondering is how to get it to the parent/root directory instead. I have fairly little experience with Vue, so I may be missing something. Thanks!

**Comment by theodore-s-beers** [comment]
Just so that you can see what I mean, I've added two new branches: `gui`, which has only the frontend source code; and `ghp2`, to which only the build output is pushed by a `deploy` script. (The existing `gh-pages` branch is untouched.)

**Comment by Jomula** [comment]
This is a relict from the main-branch used for both GUI and data. You're right, it would be more elegant to have the src, the output and the root directory clean, so if you're up to change anything in that regard feel free. Otherwise, I'll change it when there is time!

**Comment by theodore-s-beers** [comment]
Ok, I'll clean things up now.

**Comment by theodore-s-beers** [comment]
Ok, now we have the frontend source code in the `gui` branch, with a `deploy` script that pushes build output to the `gh-pages` branch, which in turn is used for GitHub Pages. Everything seems to be working.
