### ISSUE TITLE
Keywords alphabetical

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#88]
Keywords should be sorted alphabetically

**Comment by theodore-s-beers** [comment]
I took care of this in 2803ce6. Both categories and keywords are now sorted alphabetically.

Honestly, I was a bit confused by the `loadData` function in `ProjectList.vue`. But I took the "least intervention" approach to add sorting.

**Comment by Jomula** [comment]
I'm sure the `loadData` can be simplified, all it does is load the data from github raw when the site is initially loaded and when anything changes (e.g. click on keyword) and filter it depending on the category or keyword selected. As I said, a lot of last-minute-coding. :-)
