### ISSUE TITLE
Keywords Taxonomy

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#90]
It was asked if we could include topical keywords (e.g. "philosophy", "philology"), but I am a little hesitant in terms of applying to disciplinary borders that won't work in many cases, especially in the DH.
If we include keywords like that, we should probably also stick to a taxonomy, see https://vocabs.dariah.eu/
In the end, the user might want a keyword that allows to look for similar projects in a certain field. So this is to open up a discussion on how to provide that without having to stick too narrowly to the terminological boundaries of disciplines.

**Comment by XeniaMonika** [comment]
We have something similar already - the category "field" in keyword’s documentation - I can adjust these keywords to the taxonomy as much as I can, but it wouldn´t cover all our needs. For example, we have lots of projects studying historical development of religion and I  tagged them as "religion_history" (from "language_history").

So, my idea would be to stick to the taxonomy as much as we can with occasional invention of new keywords if they fit better the interdisciplinary nature of DH projects or to the field of “Arabistik”.

**Comment by Jomula** [comment]
Sounds good. Also, I'd suggest to use "religion" and "history" as keywords, instead of making it one. If that leads to more than 5 keywords in some cases, so be it. But that way we might be able to ensure sticking to the taxonomy.

**Comment by XeniaMonika** [comment]
Moved to #150
