### ISSUE TITLE
Presentation @DH23?

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#98]
I'll leave it here as an idea: We could present the project at DH23 with a Poster maybe? What do you think @theodore-s-beers @XeniaMonika

https://dh2023.adho.org/wp-content/uploads/2022/08/DH2023_CfP.pdf

**Comment by theodore-s-beers** [comment]
Sounds good to me. I would just need to double-check my calendar.

**Comment by Jomula** [comment]
> Posters (abstract 500-750 words)
Poster proposals may present work on any relevant topic, or offer demonstrations of projects, tools
and software in any stage of development. Poster presentations are intended to be interactive with
the opportunity to exchange ideas among attendees. Posters are in no way considered lesser forms
of presentation at the DH conference and are subject to the same strict peer review as other
presentation types, and submissions in this category are strongly encouraged.

**Comment by XeniaMonika** [comment]
I love the idea! The deadline is 25 of October, so we have one month... I don´t think it is that much time, right? And in case we decide to do it, how do we start?

**Comment by Jomula** [comment]
Yes, this is not much time. We need to write a project abstract and problem description, in which we make it clear that public knowledge of and contribution to the project is valuable for the DH Community. I have created a google doc, so feel free to write some points of what you think should be written in the abstract. I won't have time this week I guess, but next week I can join.

https://docs.google.com/document/d/1XeBAsXMnxbJQpuKlS-6DaYDOljQBP0_DJgKyi0E6ZQI/edit?usp=sharing

**Comment by theodore-s-beers** [comment]
> I have created a google doc, so feel free to write some points of what you think should be written in the abstract.

I've requested edit access. Can at least add a few ideas…

**Comment by Jomula** [comment]
Oh sorry, I completely forgot to open it for edit, here: https://docs.google.com/document/d/1XeBAsXMnxbJQpuKlS-6DaYDOljQBP0_DJgKyi0E6ZQI/edit?usp=sharing

I might find some time today or tomorrow to begin writing, we have 12 days to go. Managable :D

**Comment by XeniaMonika** [comment]
I already have something, I will work a bit more on it now

**Comment by theodore-s-beers** [comment]
That's a great start. I've already made some edits and can do more later.

**Comment by Jomula** [comment]
fyi: deadline extended to November 4th

**Comment by theodore-s-beers** [comment]
I just went through the whole thing again and did some copy editing etc. No major changes this time. @Jomula, hopefully it's all set for you to submit tomorrow. Thanks to you and @XeniaMonika for putting this abstract together.

**Comment by Jomula** [comment]
I have submitted our proposal but I'd rather not close the issue yet before we are accepted or rejected.

**Comment by theodore-s-beers** [comment]
Ok, I've made a conftool account for this conference. (It's slightly confusing to me that I can't have a conftool account across multiple events…) And I can see our submission. LGTM.
