### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Jomula** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#99]
I was asked if we plan to introduce a search functionality on the projects list. Might be a good idea one day but I regard it not to be the most important issue for the moment (at least not as long as there are still bugs and problems in terms of basic functionality)

**Comment by theodore-s-beers** [comment]
I do plan to implement this feature. Just haven't gotten around to it quite yet…

**Comment by theodore-s-beers** [comment]
As of today I have this working, to an extent, in the front end rebuild:

<https://ctg-redux.pages.dev/>
